# SSHコマンドに関する設定です
# 必要に応じて変更してください
#
# user: SSH接続するユーザ名
# password: SSH接続するユーザのパスワード (省略可、省略するとssh-agentを使用します)
# host: SSH接続するホスト名
# port: SSH接続するポート番号
# commands: 実行するコマンド (コマンドは1つです。thoresholdと比較するため数字で返ってくる必要があります)
# threshold: アラートを発生させるしきい値
#
servers:
  - user: "vagrant"
    host: "192.168.56.201"
    port: "22"
    commands: "sudo find /var/spool/postfix | wc -l"
    threshold: 100
  - user: "vagrant"
    host: "192.168.56.202"
    port: "22"
    commands: "sudo find /var/spool/postfix | wc -l"
    threshold: 10
  - user: "vagrant"
    host: "192.168.56.203"
    port: "22"
    commands: "sudo find /var/spool/postfix | wc -l"
    threshold: 10

# メール送信に関する設定です
# STARTTLSは未対応です.必要に応じて変更してください
#
# smtp_server: SMTPサーバのIPアドレス or ホスト名 (複数指定不可)
# smtp_port: SMTPサーバのポート番号
# from: 送信元メールアドレス
# to: 送信先メールアドレス (複数指定不可)
# subject: メールの件名
# messages: メールの本文 (アラートに付与するメッセージです。複数行可)
email:
  smtp_server: "192.168.56.201"
  smtp_port: "25"
  from: "alerts@example.com"
  to: "test1@example.com"
  subject: "Mail Queue Alert"
  messages: |
    こちらはメールキューのアラートメールです。
    メールキューがしきい値を超えました。
    