#
# SSH Command Config
#
# user: ユーザ名
# password: パスワード (省略可、省略するとssh-agentを使用します)
# host: ホスト名 or IPアドレス 
# port: ポート番号
# commands: 実行するコマンド (コマンドは1つです。thoresholdと比較するため数字で返ってくる必要があります)
# threshold: アラートを発生させるしきい値
#
servers:
  - user: "vagrant"
    password: "vagrant"
    host: "192.168.56.201"
    commands: "sudo find /var/spool/postfix/{maildrop,incoming,active,deferred,hold} -type f 2>/dev/null | wc -l"
    threshold: 0
  - user: "vagrant"
    password: "vagrant"
    host: "192.168.56.202"
    port: "22"
    commands: "sudo find /var/spool/postfix/{maildrop,incoming,active,deferred,hold} -type f 2>/dev/null | wc -l"
    threshold: 10
  - user: "vagrant"
    password: "vagrant"
    host: "192.168.56.203"
    commands: "sudo find /var/spool/postfix/{maildrop,incoming,active,deferred,hold} -type f 2>/dev/null | wc -l"
    threshold: 10

# Mail Alert Config
# メール送信に関する設定です。 STARTTLSは未対応です
#
# smtp_server: SMTPサーバのIPアドレス or ホスト名 (複数指定不可)
# smtp_port: SMTPサーバのポート番号
# from: 送信元メールアドレス
# to: 送信先メールアドレス (複数指定可)
# cc: CC送信先メールアドレス (複数指定可、省略可能)
# bcc: BCC送信先メールアドレス (複数指定可、省略可能)
# subject: メールの件名
# messages: メールの本文 (アラートに付与するメッセージです。複数行可)
email:
  smtp_server: "192.168.56.201"
  smtp_port: "25"
  from: "alerts@example.com"
  to:
    - "test1@example.com"
    - "test2@example.com"
  cc:
    - "cc1@example.com"
    - "cc2@example.com"
  bcc:
    - "bcc1@example.com"
    - "bcc2@example.com"
  subject: "Mail Queue Alert"
  messages: |
    こちらはメールキューのアラートメールです。
    メールキューがしきい値を超えました。